### ISSUE TITLE
[Bug] Installer does not install nor create log files.

### ISSUE THREAD

**Issue by Electr0wolf** [storeman-developers/harbour-storeman-installer#302]
4.5.0.21
<br /> Sony Xperia 10 III
<br />1.5.1 and 2.2.3: 
<br />

#### BUG DESCRIPTION
Running the installer, both  2.2.3. and 1.5.1, does not result in an installed Storeman app nor logfiles.

#### STEPS TO REPRODUCE
2.2.3: execute the RPM. SF OS says installation was successful. I see no installation of Storeman. No log files in /var/log/

1.5.1: execute the RPM. "Install Storeman" app appears. Run "Install Storeman". Runs for a few seconds. App stops. No message, no log in /var/log/, no Storeman app.**

#### ATTACH LOG-FILE

There is no log file available :(.

Maybe some other logfile would be able to give more information?

#### ADDITIONAL INFORMATION
Not that I know of.

**Comment by Olf0** [comment]
@Electr0wolf, thank you for your bug report.  Actually this has been reported a couple of times, but ultimately it always turned out that either people were too impatient (see [last bullet point here](https://github.com/storeman-developers/harbour-storeman-installer#features-of-storeman-installer) for details) or they did nor not answer my questions, hence I assume they discovered that Storeman did become installed by its installer.

But as you are the first one to report this under SailfishOS 4.5.0.21, let do the checks again, even though [the changes from 4.5.0.19](https://forum.sailfishos.org/t/changelog-struven-ketju-4-5-0/14291) should not affect the Storeman Installer, IMO.

a. Does `devel-su ls -l /var/log/harbour-store*` really output nothing?

b.
> Maybe some other logfile would be able to give more information?

Exactly the same log entries are logged to the systemd journal.  To see them run `journalctl -t harbour-storeman-installer` shortly after (10 - 30 seconds) after installing the `harbour-storeman-installer` RPM file.  Does that really output nothing?

**Comment by Electr0wolf** [comment]
Could find them with the terminal with devel-su. Used the file manager before, did not expect it would just totally ignore files and directories that it has no access to.

Don't have the time to fully copy the logs, but two things caught my attention:

- [only on 1.5.1, not 2.2.3] WARNING: ssu.ini does not seem to be writable. Setting values might not work.
- In step 2: Command failed: This tool could not find any available package.

It does seem that step 1 works ok.

**Comment by Olf0** [comment]
> It does seem that step 1 works ok.

Yes.  The warning for Storeman Installer v1.x.y is normal, because it runs in user context; it is just a warning (which is harmless, the way Storeman Installer uses `ssu`), not an error.

For step 2: The package should now be available (this was something I really missed for SFOS 4.5.0.21).

**Comment by Electr0wolf** [comment]
Just installed Storeman with 1.5.1 after a pkcon refresh and cache reset. Seems to behave as expected now!
