### ISSUE TITLE
[Bug] Storeman Installer v2.2.8 fails on SailfishOS ≥ 4.6.0

### ISSUE THREAD

**Issue by norayr** [storeman-developers/harbour-storeman-installer#318]
**SailfishOS VERSION** (Settings → About product → Build): 4.6.0.15 (sauna)
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Sony Xrepia XA2 Dual Sim
<br />**Storeman Installer VERSION**: 2.2.8-release9
<br />

#### BUG DESCRIPTION
i have downloaded latest harbour-storeman-installer, built on november 11.
https://openrepos.net/sites/default/files/packages/5928/harbour-storeman-installer-2.2.8-release9.noarch.rpm

after installation i see the log:
[harbour-storeman-installer.log.txt](https://github.com/user-attachments/files/17892163/harbour-storeman-installer.log.txt)

i tried several times and my connection is okay.

#### ATTACH LOG-FILE

Upload the log-file from `/var/log/harbour-storeman-installer.log.txt` here.
see above

#### ADDITIONAL INFORMATION

<sub>\[Please consider which other pieces of information may be relevant: Denote if this is not always reproducible, if this is a regression (then name to which older version), attach relevant data such as log files or the systemd journal, provide screenshots etc.\]</sub>

**Comment by norayr** [comment]
btw i dont know why ssu status reports the device as not registered: i got alien dalvik from jolla, and i am logged in to jolla account. but it shouldnt matter for openrepos anyway i guess.

**Comment by HenriVSL** [comment]
I can report same issue with Jolla C2 on 5.0.0.29.

Log is pretty much the same. (I'll include it later after I have dumped it.)

**Comment by Olf0** [comment]
@norayr and @HenriVSL, thank you very much for filing a proper bug report here at GitHub!  I read that people had issues using the Storeman Installer at FSO, but I gave up reacting to "does not work" messages there, because most users react aversive when asked to file a proper bug report.

From the log files I see that for both of you the `%post` scriptlet in the RPM spec file [failed to add the `harbour-storeman-obs` repository to SSU](https://github.com/storeman-developers/harbour-storeman-installer/blob/devel/rpm/harbour-storeman-installer.spec#L176-L196) (Nokia's / Jolla's "Seamless Software Updater").

As I reworked exactly this section of the `%post` scriptlet for Storeman Installer v2.2.7 and v2.2.8 which performs this, can you please run these three tests.
<sub>Side note: Jolla's "Terminal" app for accessing the command line is installed when you activate in Jolla's `Settings` app `Developer tools`**→**`Developer mode`, and then set a `ssh` password after activating `Remote connection`; you can then also log-in to your SailfishOS device from your PC or laptop by using `ssh` / `slogin` on Linux or `putty` on Windows.</sub>
1. At the command line, please run (no root required):
   `source /etc/os-release; echo "$VERSION_ID" | cut -s -f 1-3 -d '.' | tr -d '.' | grep '^[0-9][0-9][0-9][0-9]*$'`
   This should output `460` (on a device with SailfishOS 4.6.0.x installed), respectively `500` (on a device with SailfishOS 5.0.0.x installed).
2. At the command line, please run (no root required):
   `grep '^harbour-storeman-obs=' /etc/ssu/ssu.ini | grep -o '/[[:graph:]][[:graph:]][[:graph:]][[:graph:]]*/$' | grep -o '%(release[[:alpha:]]*)'`
   This should output nothing on your devices currently (but also no error message etc., just nothing).
3. Please download and install Storeman Installer v2.2.6, either [from GitHub](https://github.com/storeman-developers/harbour-storeman-installer/releases/tag/release7%2F2.2.6) or [OpenRepos](https://openrepos.net/content/olf/storeman-installer) (both offer exactly the same version compiled at GitHub).
   After waiting for 10 seconds, does Storeman become installed?

* If step 3 went fine (i.e. Storeman became installed), please rerun step 2: It should now output `%(releaseMajorMinor)` (*exactly* that).  Then remove Storeman (e.g. by long pressing on Storeman's launcher icon) and try Storeman Installer v2.2.7 in order to narrow the changes which introduced the flaw.
* If step 3 did not work (i.e. Storeman did not become installed), please rerun step 2: Does it still output nothing?

P.S.: Thank you very much for your help, I currently do not run a device with SailfishOS 4.6.0 or 5.0.0.

P.P.S.:
> btw i dont know why ssu status reports the device as not registered:

This is "normal": No matter if you have obtained a licence for SailfishOS or use its "trial" version (or even a community port of SailfishOS), SSU's `Device registration status` is always `not registered`.

> but it shouldnt matter for openrepos anyway i guess.

Correct.

**Comment by HenriVSL** [comment]
Sorry it took some time. Version 2.2.6 worked and also 2.2.7. First command returned 500.
And after install I ran the command which returned the following:

`[defaultuser@JollaC2 ~]$ grep '^harbour-storeman-obs=' /etc/ssu/ssu.ini | grep -o '/[[:graph:]][[:graph:]][[:graph:]][[:graph:]]*/$' | grep
-o '%(release[[:alpha:]]*)'
%(releaseMajorMinor)
`

**Comment by Olf0** [comment]
> Sorry it took some time.

Huh, less than a day is much faster than I usually am.

> Version 2.2.6 worked and also 2.2.7.

Thank you very much for your testing.  Thus I retracted v2.2.8.

> First command returned 500. And after install I ran the command which returned the following:
> `[defaultuser@JollaC2 ~]$ grep '^harbour-storeman-obs=' /etc/ssu/ssu.ini | grep -o '/[[:graph:]][[:graph:]][[:graph:]][[:graph:]]*/$' | grep -o '%(release[[:alpha:]]*)'`
> `%(releaseMajorMinor)`

Perfect: So I basically did everything right.

I reviewed [the changes between v2.2.6 and v2.2.8](https://github.com/storeman-developers/harbour-storeman-installer/compare/release7/2.2.6...release9/2.2.8) yesterday and did not spot the flaw I introduced.  It should be easier to find now, as I now know it must be some of [the changes between v2.2.7 and v2.2.8](https://github.com/storeman-developers/harbour-storeman-installer/compare/release8/2.2.7...release9/2.2.8).  I will review again, likely it is some typo or "think'o" I am just too blind to see.

**Comment by Olf0** [comment]
Yes, I was too blind to spot the missing `$` to evaluate a variable in the first place, see commit 3ffb000.

I will create a new release soon (really, not "Jolla soon™").

**Comment by HenriVSL** [comment]
I'm glad I was help!

**Comment by Olf0** [comment]
> I'm glad I was help!

We are not done yet: You may test the new version I will release in a couple of minutes.

**Comment by Olf0** [comment]
> You may test the new version I will release in a couple of minutes.

Here you go: [releases/tag/release10/2.3.0](https://github.com/storeman-developers/harbour-storeman-installer/releases/tag/release10%2F2.3.0)

**Comment by HenriVSL** [comment]
I tested the 2.3.0 build and verified it to work as it should.

**Comment by Olf0** [comment]
Thank you very much.

This was the verification I hoped for before I dare to upload Storeman Installer v2.3.0 to OpenRepos (after the mishap with v2.2.8): [Done now](https://openrepos.net/content/olf/storeman-installer#block-system-main).

**Comment by norayr** [comment]
just released 2.3.0 works! thank you!

**Comment by Olf0** [comment]
> just released 2.3.0 works! 

Thanks for verifying Storeman Installer 2.3.0 on an XperiaXA2@SFOS4.6.0.
