### ISSUE TITLE
Storeman Installer at Chum

### ISSUE THREAD

**Issue by rinigus** [storeman-developers/harbour-storeman-installer#37]
Please decide whether you wish to have Storeman Installer in Chum or not. On your request, I removed it from sailfishos:chum but left in sailfishos:chum:testing. According to Chum design, I would expect to have the same packages in the both. So, if you don't want to have the installer in sailfishos:chum, we should drop it from sailfishos:chum:testing as well.

**Comment by Olf0** [comment]
As you want it in either in both, SailfishOS:Chum and SailfishOS:Chum testing, or none, I rather choose "both". :slightly_smiling_face:

**Comment by rinigus** [comment]
Understood! Then I will add it back

**Comment by Gaspartame** [comment]
Was it added in the end ? I can't find it in Chum Gui

**Comment by Olf0** [comment]
Yes, back in march '22, and taken out again more than a year later to reduce my maintenance load.

Since then I solely publish it [at OpenRepos](https://openrepos.net/content/olf/storeman-installer);
for details see [the Storeman-Installer README](https://github.com/storeman-developers/harbour-storeman-installer#readme).
